" no vi compatibility
set nocompatible

" Show position in file
set ruler

" Show line numbers
set number

set novisualbell  " No blinking .
set noerrorbells  " No noise.
set laststatus=2  " Always show status line.

set autoindent
set smartindent

" Use 2 spaces for tabs, turn on automatic indenting
set tabstop=4 softtabstop=2 shiftwidth=2 expandtab
set smarttab
set backspace=start,indent

" highlight tabs and trailing spaces
set listchars=trail:.,tab:>-
set list

" Turn on highlighted search and syntax highlighting
set hlsearch
set incsearch
syntax on
set nofoldenable

" Set hidden mode
set hidden

" Turn on line highlighting
"set cursorline " Commented out due to performance penalties

" Disable backup and swapfile
set nobackup
set noswapfile
set nowritebackup

" Enable mouse in console
set mouse=a

" Tab completion in command line
set wildmode=longest,list

" Set leader to comma
let mapleader = ","

" Remap : to ;
nnoremap ; :

" Jump more naturally between long lines
nnoremap j gj
nnoremap k gk

" Easy window navigation
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Unhighlight search
nmap <silent> ,/ :nohlsearch<CR>

" Set up command for NERDTree
map <leader>n :NERDTreeToggle<CR>

" Lusty Buffer options
map <leader>f :LustyFilesystemExplorer<cr>
map <leader>b :LustyJuggler<cr>
map <leader>g :LustyBufferGrep<cr>

" Make backspace work the way it should
set backspace=2

" Make backspace and cursor keys wrap accordingly"
set whichwrap+=<,>,h,l

" Make searches case-insensitive
set ignorecase

" Make editing .vimrc easier
map <leader>z :sp ~/.vimrc<CR>
map <leader>Z :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Copy and paste
map <leader>v "*p<CR>:exe ":echo 'pasted from clipboard'"<CR>
map <leader>c "*y<CR>:exe ":echo 'copied to clipboard'"<CR>

map <leader>B :BufOnly<CR>

" Generate a tags file in the current directory using Exuberant ctags
map <leader>e :silent :! ctags --recurse --sort=yes;sort tags > tmptags;mv tmptags tags<CR>:exe ":echo 'tags generated'"<CR>

filetype off

call pathogen#runtime_append_all_bundles()
let coffee_compile_on_save = 0

filetype plugin indent on

function! AckGrep(command)
  cexpr system("ack -a" . a:command)
  cw
endfunction

command! -nargs=+ -complete=file Ack call AckGrep(<q-args>)

map <leader>a :Ack<space>

" Add a status line by default
"set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
"set laststatus=2
" Session saving
set sessionoptions=blank,buffers,curdir,folds,help,resize,tabpages,winsize

" Ruby folding
" au Filetype ruby call <Plug>SimpleFold_Foldsearch

" Omni Completion
" *************************************************************
autocmd FileType html :set omnifunc=htmlcomplete#CompleteTags
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
" May require ruby compiled in
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete 

" Solarized
set background=dark
colorscheme solarized

" Show title
set title

" Erlang options
let g:erlangManPath='/usr/local/Cellar/erlang/R13B04/share/man'
let g:erlangHighlightBif=1
let g:erlangCompleteFile="~/.vim/bundle/vimerl/autoload/erlang_complete.erl"
let g:erlangCheckFile="~/.vim/bundle/vimerl/compiler/erlang_check.erl"
