" no vi compatibility
set nocompatible

" Show position in file
set ruler

" Show line numbers
set number

set novisualbell  " No blinking .
set noerrorbells  " No noise.
set laststatus=2  " Always show status line.

set autoindent
set smartindent

" Use 2 spaces for tabs, turn on automatic indenting
set tabstop=4 softtabstop=2 shiftwidth=2 expandtab
set smarttab
set backspace=start,indent

" highlight tabs and trailing spaces
set listchars=trail:.,tab:>-
set list

" Turn on highlighted search and syntax highlighting
set hlsearch
set incsearch
syntax on
set foldmethod=manual

" Turn on line highlighting
set cursorline " Commented out due to performance penalties

" Set colorscheme
if has("gui_running")
	colorscheme wombat
	set guifont=Anonymous:h12
endif 

" Set backup directory
set backupdir=~/.vim/tmp
set directory=~/.vim/tmp

" Set leader to comma
let mapleader = ","

" Set up commands for FuzzyFinder and FuzzyFinderTextMate
map <leader>t :FuzzyFinderTextMate<CR>
map <leader>f :FuzzyFinderFile<CR>
map <leader>r :FuzzyFinderMruFile<CR>
map <leader>R :ruby finder.rescan!<CR>:FuzzyFinderRemoveCache<CR>:exe ":echo 'rescan complete'"<CR>

" Fuzzy options
let g:fuzzy_ignore = "*.log"
let g:fuzzy_matching_limit = 70

" Set up command for NERDTree
map <leader>n :NERDTreeToggle<CR>

" MiniBufExplr
map <leader>b :MiniBufExplorer<cr>

" Make backspace work the way it should
set backspace=2

" Make backspace and cursor keys wrap accordingly"
set whichwrap+=<,>,h,l

" Make searches case-insensitive
set ignorecase

" Make editing .vimrc easier
map <leader>v :sp ~/.vimrc<CR>
map <leader>V :source ~/.vimrc<CR>:filetype detect<CR>:exe ":echo 'vimrc reloaded'"<CR>

" Generate a tags file in the current directory using Exuberant ctags
map <leader>e :silent :! ctags --recurse --sort=yes;sort tags > tmptags;mv tmptags tags<CR>:exe ":echo 'tags generated'"<CR>

filetype off

call pathogen#runtime_append_all_bundles()
let coffee_compile_on_save = 1

filetype plugin indent on

function! AckGrep(command)
  cexpr system("ack -a" . a:command)
  cw
endfunction

command! -nargs=+ -complete=file Ack call AckGrep(<q-args>)

map <leader>a :Ack<space>

" Add a status line by default
"set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
"set laststatus=2
" Session saving
set sessionoptions=blank,buffers,curdir,folds,help,resize,tabpages,winsize

" Ruby folding
" au Filetype ruby call <Plug>SimpleFold_Foldsearch

" Omni Completion
" *************************************************************
autocmd FileType html :set omnifunc=htmlcomplete#CompleteTags
autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType xml set omnifunc=xmlcomplete#CompleteTags
autocmd FileType php set omnifunc=phpcomplete#CompletePHP
autocmd FileType c set omnifunc=ccomplete#Complete
" May require ruby compiled in
autocmd FileType ruby,eruby set omnifunc=rubycomplete#Complete 
