alias bundle='nocorrect bundle'
alias rspec='nocorrect rspec'
alias 'make eunit'='nocorrect make eunit'
alias t='tail -F'

export EDITOR=vim

# rvm
unsetopt auto_name_dirs
if [ -s ~/.rvm/scripts/rvm ] ; then source ~/.rvm/scripts/rvm ; fi

# rbenv
#eval "$(rbenv init -)"

# ohmyzsh options
export DISABLE_AUTO_UPDATE="true"
plugins=(git)

if [ `uname` = "Darwin" ]; then
  # dev
  export ZSH_THEME="macovsky"

  ulimit -n 2056
  export PATH=/usr/local/bin:$PATH
  export NODE_PATH=/usr/local/lib/node_modules
elif [ `uname` == "Linux" ]; then
  # server
fi

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh
