alias bundle='nocorrect bundle'
alias rspec='nocorrect rspec'
alias 'make eunit'='nocorrect make eunit'
alias t='tail -F'
alias sr='find . -type f|xargs perl -pi -e '

export EDITOR=vim

# add custom completion scripts
fpath=(~/.zsh/completions $fpath)

# show completion menu when number of options is at least 2
zstyle ':completion:*' menu select=2

tm() {
  [[ -z "$1" ]] && { echo "usage: tm <session>" >&2; return 1; }
  tmux has -t $1 && tmux attach -d -t $1 || tmux new -s $1
}


# ohmyzsh options
export DISABLE_AUTO_UPDATE="true"
plugins=(git)

if [[ `uname` = "Darwin" ]]; then
  # dev
  export ZSH_THEME="macovsky"

  ulimit -n 2056
  export PATH=/usr/local/bin:$PATH
  export NODE_PATH=/usr/local/lib/node_modules
elif [[ `uname` == "Linux" ]]; then
  # server
fi

# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

source $ZSH/oh-my-zsh.sh

# record directory in ~/.lastpwd
record_pwd() {
  pwd > ~/.lastpwd
}
chpwd_functions=(record_pwd)

# go to last directory when opening a new shell
if [[ -d `cat ~/.lastpwd` ]]; then
  cd `cat ~/.lastpwd`
fi

export PATH="/usr/local/sbin:$PATH"
